{
 "title": "In-Network Attack Detection",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "chunk_length_sec", "label": "Chunk length (sec)", "query": "${VAR_CHUNK_LENGTH_SEC}" },
   { "name": "short_chunk_length_sec", "label": "Short chunk length (sec)", "query": "${VAR_SHORT_CHUNK_LENGTH_SEC}" }
  ]
 },
 "panels": [
  {
   "title": "Flow counts & accuracy over time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "select time, 1 as \"New model deployed\"\r\nfrom model_deployment\r\nWHERE $__timeFilter(time)"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT\r\n  DATE_BIN(INTERVAL $chunk_length_sec, to_timestamp(time::bigint + ($chunk_length_sec * 1000000000) / 1)) as bucket,\r\n  SUM(CASE WHEN true_label = 1 THEN 1 ELSE 0 END) / $chunk_length_sec AS \"Started benign flows / sec\"\r\nFROM flow\r\nWHERE $__timeFilter(time)\r\nGROUP BY bucket\r\nORDER BY bucket"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT\r\n  DATE_BIN(INTERVAL $chunk_length_sec, to_timestamp(time::bigint + ($chunk_length_sec * 1000000000) / 1)) as bucket,\r\n  SUM(CASE WHEN true_label = 2 THEN 1 ELSE 0 END) / $chunk_length_sec AS \"Started attack flows / sec\"\r\nFROM flow\r\nWHERE $__timeFilter(time)\r\nGROUP BY bucket\r\nORDER BY bucket"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT\r\n  DATE_BIN(INTERVAL $short_chunk_length_sec, to_timestamp(time::bigint + ($short_chunk_length_sec * 1000000000) / 1)) as bucket,\r\n  AVG(CASE WHEN (predicted_label = true_label) or (predicted_label = 0 and true_label = 1) THEN 1 ELSE 0 END) AS \"Accuracy\"\r\nFROM flow\r\nWHERE $__timeFilter(time)\r\nGROUP BY bucket\r\nORDER BY bucket"
    }
   ]
  },
  {
   "title": "Confusion matrix",
   "type": "canvas",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\r\n  AVG(CASE WHEN predicted_label = 2       AND true_label = 2 THEN 1 ELSE 0 END) AS pred_a_true_a,\r\n  AVG(CASE WHEN predicted_label = 2       AND true_label = 1 THEN 1 ELSE 0 END) AS pred_a_true_b,\r\n  AVG(CASE WHEN predicted_label IN (0, 1) AND true_label = 1 THEN 1 ELSE 0 END) AS pred_b_true_b,\r\n  AVG(CASE WHEN predicted_label IN (0, 1) AND true_label = 2 THEN 1 ELSE 0 END) AS pred_b_true_a\r\nFROM flow\r\nWHERE $__timeFilter(time)"
    }
   ]
  },
  {
   "title": "Started flows over time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\r\n  DATE_BIN(INTERVAL $short_chunk_length_sec, to_timestamp(time::bigint + ($short_chunk_length_sec * 1000000000) / 1)) as bucket,\r\n  COUNT(*) AS \"Total flow count\"\r\nFROM flow\r\nWHERE $__timeFilter(time)\r\nGROUP BY bucket\r\nORDER BY bucket"
    }
   ]
  },
  {
   "title": "Percentage of monitored flows",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "WITH flow_buckets AS (\r\n    SELECT\r\n        date_bin(INTERVAL $chunk_length_sec, to_timestamp(time::bigint + ($chunk_length_sec * 1000000000) / 1)) as window,\r\n        COUNT(*) AS flow_count\r\n    FROM flow\r\n    WHERE $__timeFilter(time)\r\n    GROUP BY window\r\n),\r\nmonitored_buckets AS (\r\n    SELECT\r\n        date_bin(INTERVAL $chunk_length_sec, to_timestamp(time::bigint + ($chunk_length_sec * 1000000000) / 2)) AS window,\r\n        SUM(count) AS total_count\r\n    FROM monitored_flow_count\r\n    WHERE $__timeFilter(time)\r\n    GROUP BY window\r\n)\r\nSELECT\r\n    m.window,\r\n    100.0 * m.total_count / f.flow_count AS \"% of monitored flows\"\r\nFROM monitored_buckets m\r\nINNER JOIN flow_buckets f ON m.window = f.window\r\nWHERE m.window < (SELECT MAX(x.window) FROM monitored_buckets x)\r\n  AND m.window < (SELECT MAX(x.window) FROM flow_buckets x)\r\n  AND (100.0 * m.total_count / f.flow_count) > 0.1\r\n  AND (100.0 * m.total_count / f.flow_count) < 20\r\nORDER BY m.window;"
    }
   ]
  },
  {
   "title": "Overall accuraccy",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\r\n  AVG(CASE WHEN (predicted_label = true_label) or (predicted_label = 0 and true_label = 1) THEN 1 ELSE 0 END) AS \"Overall accuracy\"\r\nFROM flow\r\nWHERE $__timeFilter(time)"
    }
   ]
  },
  {
   "title": "Overall F1 score",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "WITH counts AS (\r\n  SELECT\r\n    SUM(CASE WHEN predicted_label = 2 AND true_label = 2 THEN 1 ELSE 0 END) AS tp,\r\n    SUM(CASE WHEN predicted_label = 2 AND true_label IN (0, 1) THEN 1 ELSE 0 END) AS fp,\r\n    SUM(CASE WHEN predicted_label IN (0, 1) AND true_label = 2 THEN 1 ELSE 0 END) AS fn\r\n  FROM flow\r\n  WHERE $__timeFilter(time)\r\n),\r\nmetrics AS (\r\n  SELECT\r\n    tp,\r\n    fp,\r\n    fn,\r\n    CASE WHEN (tp + fp) > 0 THEN tp * 1.0 / (tp + fp) ELSE 0 END AS precision,\r\n    CASE WHEN (tp + fn) > 0 THEN tp * 1.0 / (tp + fn) ELSE 0 END AS recall\r\n  FROM counts\r\n),\r\nf1_calc AS (\r\n  SELECT\r\n    precision,\r\n    recall,\r\n    CASE\r\n      WHEN (precision + recall) > 0\r\n      THEN 2 * precision * recall / (precision + recall)\r\n      ELSE 0\r\n    END AS f1_score\r\n  FROM metrics\r\n)\r\nSELECT f1_score as \"Overall F1 score\" FROM f1_calc\r\n"
    }
   ]
  },
  {
   "title": "Model information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Model scores over time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "dataset": "iox",
       "rawSql": "SELECT time, f1_score as 'Estimated F1 score of current model'\r\nFROM time_window_score\r\nWHERE type = 'current_estimate' AND $__timeFilter(time)"
      },
      {
       "dataset": "iox",
       "rawSql": "SELECT time, f1_score as 'Estimated F1 score of new model'\r\nFROM time_window_score\r\nWHERE type = 'new_estimate' AND $__timeFilter(time)"
      },
      {
       "dataset": "iox",
       "rawSql": "SELECT time, f1_score as 'Actual F1 score of deployed models'\r\nFROM time_window_score\r\nWHERE type = 'current_actual' AND $__timeFilter(time)"
      }
     ]
    },
    {
     "title": "Model deployments",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "dataset": "iox",
       "rawSql": "select to_timestamp(time::bigint - 100000000) as x, 0 as y\r\nfrom model_deployment\r\nWHERE $__timeFilter(time)\r\n\r\nunion\r\n\r\nselect time as x, 1 as y\r\nfrom model_deployment\r\nWHERE $__timeFilter(time)\r\n\r\nunion\r\n\r\nselect to_timestamp(end_time) as x, 1 as y\r\nfrom model_deployment\r\nWHERE $__timeFilter(time)\r\n\r\nunion\r\n\r\nselect to_timestamp(end_time + 100000000) as x, 0 as y\r\nfrom model_deployment\r\nWHERE $__timeFilter(time)\r\n"
      },
      {
       "dataset": "iox",
       "rawSql": "select to_timestamp(time::bigint + duration / 2), complexity as \"Complexity of new model\"\r\nfrom model_deployment\r\nWHERE $__timeFilter(time)"
      }
     ]
    }
   ]
  },
  {
   "title": "Combined graphs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Combined graph",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "dataset": "iox",
       "rawSql": "SELECT time, f1_score as 'Estimated F1 score of current model'\r\nFROM time_window_score\r\nWHERE type = 'current_estimate' AND $__timeFilter(time)"
      },
      {
       "dataset": "iox",
       "rawSql": "SELECT time, f1_score as 'Estimated F1 score of new model'\r\nFROM time_window_score\r\nWHERE type = 'new_estimate' AND $__timeFilter(time)"
      },
      {
       "dataset": "iox",
       "rawSql": "SELECT time, f1_score as 'Actual F1 score of deployed models'\r\nFROM time_window_score\r\nWHERE type = 'current_actual' AND $__timeFilter(time)"
      },
      {
       "dataset": "iox",
       "rawSql": "select time, 1 as \"New model deployed\"\r\nfrom model_deployment\r\nWHERE $__timeFilter(time)"
      },
      {
       "dataset": "iox",
       "rawSql": "SELECT\r\n  DATE_BIN(INTERVAL $chunk_length_sec, to_timestamp(time::bigint + ($chunk_length_sec * 1000000000) / 1)) as bucket,\r\n  SUM(CASE WHEN true_label = 1 THEN 1 ELSE 0 END) / $chunk_length_sec AS \"Started benign flows / sec\"\r\nFROM flow\r\nWHERE $__timeFilter(time)\r\nGROUP BY bucket\r\nORDER BY bucket"
      },
      {
       "dataset": "iox",
       "rawSql": "SELECT\r\n  DATE_BIN(INTERVAL $chunk_length_sec, to_timestamp(time::bigint + ($chunk_length_sec * 1000000000) / 1)) as bucket,\r\n  SUM(CASE WHEN true_label = 2 THEN 1 ELSE 0 END) / $chunk_length_sec AS \"Started attack flows / sec\"\r\nFROM flow\r\nWHERE $__timeFilter(time)\r\nGROUP BY bucket\r\nORDER BY bucket"
      },
      {
       "dataset": "iox",
       "rawSql": "SELECT\r\n  DATE_BIN(INTERVAL $short_chunk_length_sec, to_timestamp(time::bigint + ($chunk_length_sec * 1000000000) / 1)) as bucket,\r\n  AVG(CASE WHEN (predicted_label = true_label) or (predicted_label = 0 and true_label = 1) THEN 1 ELSE 0 END) AS \"Accuracy\"\r\nFROM flow\r\nWHERE $__timeFilter(time)\r\nGROUP BY bucket\r\nORDER BY bucket"
      }
     ]
    }
   ]
  }
 ]
}